"""rename address

Revision ID: 1385e015aa7f
Revises: bdff6ae08e8d
Create Date: 2024-06-27 00:50:17.078477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1385e015aa7f'
down_revision = 'bdff6ae08e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # with op.batch_alter_table('departments', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
    #     batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # with op.batch_alter_table('departments', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
    #     batch_op.drop_column('location')

    # ### end Alembic commands ###
